const SUPABASE_URL='https://oslkpuqkppxvbyvegvkn.supabase.co';
const API_KEY='sb_publishable_jXx0SQQ3wCxx3Ohphrs68w_iYeys-nz';
const SESSION_KEY='apart-tid-session';
const INSTALL_DISMISSED='apart-tid-admin-install-dismissed';
const $=selector=>document.querySelector(selector);

let session=null,currentAdmin=null,selectedDate='',dashboardData=null,rosterData={shifts:[],employees:[],absences:[]},loginEmail='',deferredInstallPrompt=null,pwaRegistration=null,pwaRefreshing=false;

function show(message){const element=$('#toast');element.textContent=message;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),3400)}
function escapeHtml(value){const div=document.createElement('div');div.textContent=String(value??'');return div.innerHTML}
function saveSession(value){session=value;if(value)localStorage.setItem(SESSION_KEY,JSON.stringify(value));else localStorage.removeItem(SESSION_KEY)}
async function request(path,{method='GET',body,token}={}){const response=await fetch(SUPABASE_URL+path,{method,headers:{apikey:API_KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error_description||data.msg||data.error||'Noe gikk galt. Prøv igjen.');return data}
async function refreshSession(){if(!session?.refresh_token)return false;try{const data=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}});saveSession(data);return true}catch{return false}}
async function authenticated(path,options={}){if(!session?.access_token)throw new Error('Du må logge inn.');try{return await request(path,{...options,token:session.access_token})}catch(error){if(/jwt|token|expired/i.test(error.message)&&await refreshSession())return request(path,{...options,token:session.access_token});throw error}}
async function getMe(){const rows=await authenticated('/rest/v1/employees?select=id,employee_number,full_name,email,role,active&auth_user_id=eq.'+encodeURIComponent(session.user.id));return rows[0]}

function localDate(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function addDays(value,days){const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
function monday(value){const date=new Date(`${value}T12:00:00Z`),day=date.getUTCDay()||7;date.setUTCDate(date.getUTCDate()-day+1);return date.toISOString().slice(0,10)}
function dateText(value){return new Date(`${value}T12:00:00Z`).toLocaleDateString('nb-NO',{timeZone:'Europe/Oslo',weekday:'long',day:'numeric',month:'long'})}
function rosterMinutes(value){const[hour,minute]=String(value||'').slice(0,5).split(':').map(Number);return hour*60+minute}
function rosterTime(value){return String(value||'').slice(0,5).replace(':','.')}
function crossesMidnight(shift){return rosterMinutes(shift.end_time)<=rosterMinutes(shift.start_time)}
function shiftLabel(shift){if(shift.shift_type==='day')return'Dagskift';if(shift.shift_type==='evening')return'Kveldsskift';return rosterMinutes(shift.start_time)>=720?'Nattskift 1':'Nattskift 2'}
function shiftInterval(shift){const base=new Date(`${shift.work_date}T00:00:00Z`).getTime(),start=base+rosterMinutes(shift.start_time)*60000;let end=base+rosterMinutes(shift.end_time)*60000;if(end<=start)end+=86400000;return[start,end]}
function absenceLabel(absence){return absence.request_type==='sick_leave'?'Sykefravær':absence.request_type==='vacation'?'Ferie':'Permisjon'}

async function openApp(){try{const me=await getMe();if(!me?.active)throw new Error('Brukeren er ikke aktiv.');if(me.role!=='admin')throw new Error('Denne appen er bare tilgjengelig for administrator. Åpne fullversjonen for vanlig ansattvisning.');currentAdmin=me;$('#login').classList.add('hidden');$('#adminApp').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#welcome').textContent=`Hei, ${me.full_name.split(/\s+/)[0]}.`;$('#identity').textContent=`${me.employee_number} · ${me.email}`;selectedDate=localDate();await loadDay()}catch(error){show(error.message)}}

async function loadDay(){const week=monday(selectedDate);[dashboardData,rosterData]=await Promise.all([authenticated(`/functions/v1/admin-dashboard?date=${selectedDate}`),authenticated(`/functions/v1/roster?week=${week}`)]);renderDay()}
function renderDay(){const isToday=selectedDate===localDate(),isTomorrow=selectedDate===addDays(localDate(),1),summary=dashboardData.summary;$('#dateHeading').textContent=isToday?'I dag':isTomorrow?'I morgen':new Date(`${selectedDate}T12:00:00Z`).toLocaleDateString('nb-NO',{timeZone:'Europe/Oslo',weekday:'long'});$('#dateLabel').textContent=dateText(selectedDate);$('#summary').innerHTML=`<article class="admin-app-stat"><span>Planlagt på jobb</span><strong>${summary.expected}</strong></article><article class="admin-app-stat ${isToday?'clocked':''}"><span>${isToday?'Stemplet inn nå':'Innstempling'}</span><strong>${summary.clocked_in==null?'–':summary.clocked_in}</strong></article><article class="admin-app-stat"><span>Planlagte timer</span><strong>${summary.planned_hours==null?'–':Number(summary.planned_hours).toLocaleString('nb-NO',{maximumFractionDigits:2})+' t'}</strong></article><article class="admin-app-stat"><span>Krever behandling</span><strong>${summary.tasks}</strong></article>`;renderShifts();renderTasks()}
function shiftState(shift){const person=(dashboardData.people||[]).find(item=>item.id===shift.employee_id);return person?.status==='clocked_in'?{label:'Stemplet inn',className:'clocked'}:person?.status==='away'?{label:person.status_label,className:'away'}:{label:'Planlagt',className:'planned'}}
function renderShifts(){const schedule=rosterData.schedule,status=schedule?.status||'draft',dirty=Boolean(schedule?.published_at&&new Date(schedule.updated_at)>new Date(schedule.published_at));$('#rosterStatus').textContent=status==='published'?(dirty?'Upublisert':'Publisert'):status==='inactive'?'Inaktiv':'Utkast';$('#rosterStatus').className=`status ${dirty?'pending':status}`;const shifts=(rosterData.shifts||[]).filter(shift=>shift.work_date===selectedDate).sort((a,b)=>String(a.start_time).localeCompare(String(b.start_time)));$('#shiftList').innerHTML=shifts.length?shifts.map(shift=>{const employee=rosterData.employees.find(item=>item.id===shift.employee_id),state=shiftState(shift);return `<button class="admin-app-shift ${shift.shift_type}" data-shift-id="${shift.id}"><span class="admin-app-shift-time">${rosterTime(shift.start_time)}–${rosterTime(shift.end_time)}</span><span class="admin-app-shift-person"><strong>${escapeHtml(employee?.full_name||'Ukjent ansatt')}</strong><small>${shiftLabel(shift)}${crossesMidnight(shift)?' · neste dag':''}</small></span><span class="admin-app-shift-state ${state.className}">${escapeHtml(state.label)}</span><span class="admin-app-shift-arrow">›</span></button>`}).join(''):'<div class="empty">Ingen vakter er satt opp denne dagen.</div>';const absences=(rosterData.absences||[]).filter(item=>item.start_date<=selectedDate&&item.end_date>=selectedDate);$('#absenceList').innerHTML=absences.length?`<strong>Registrert fravær</strong>${absences.map(absence=>{const employee=rosterData.employees.find(item=>item.id===absence.employee_id);return `<span>${escapeHtml(employee?.full_name||'Ansatt')} · ${absenceLabel(absence)}</span>`}).join('')}`:''}
function renderTasks(){const tasks=dashboardData.tasks||[];$('#taskBadge').textContent=`${dashboardData.summary.tasks} åpne`;$('#taskList').innerHTML=tasks.map(task=>`<article class="admin-app-task"><span class="admin-app-task-icon">${({vacation:'F',hms:'H',contract:'K',clock:'T'})[task.type]||'•'}</span><span><strong>${escapeHtml(task.label)}</strong><small>${escapeHtml(task.detail)}</small></span><span class="status ${task.count?'pending':'active'}">${task.count||'✓'}</span></article>`).join('')}

function unavailableReason(employeeId,shift){const absence=(rosterData.absences||[]).find(item=>item.employee_id===employeeId&&item.start_date<=shift.work_date&&item.end_date>=shift.work_date);if(absence)return absenceLabel(absence);const[from,to]=shiftInterval(shift),overlap=(rosterData.shifts||[]).some(item=>item.id!==shift.id&&item.employee_id===employeeId&&(()=>{const[a,b]=shiftInterval(item);return from<b&&to>a})());return overlap?'Overlappende vakt':''}
function openQuickShift(id){const shift=(rosterData.shifts||[]).find(item=>item.id===id);if(!shift)return;$('#quickShiftId').value=shift.id;$('#quickShiftHeading').textContent=`Bytt ansatt · ${dateText(shift.work_date)}`;$('#quickShiftDetails').innerHTML=`<strong>${escapeHtml(shiftLabel(shift))}</strong><span>${rosterTime(shift.start_time)}–${rosterTime(shift.end_time)}${crossesMidnight(shift)?' · neste dag':''}</span>`;$('#quickShiftReason').value='';$('#quickShiftAvailability').classList.add('hidden');$('#quickShiftEmployee').innerHTML='<option value="">Velg ansatt</option>'+rosterData.employees.map(employee=>{const unavailable=unavailableReason(employee.id,shift),current=employee.id===shift.employee_id;return `<option value="${employee.id}" ${current?'selected':''} ${unavailable&&!current?'disabled':''}>${escapeHtml(employee.employee_number)} · ${escapeHtml(employee.full_name)}${unavailable?` · ${escapeHtml(unavailable)}`:''}</option>`}).join('');$('#quickShiftDialog').showModal()}
function updateAvailability(){const shift=(rosterData.shifts||[]).find(item=>item.id===$('#quickShiftId').value),employee=rosterData.employees.find(item=>item.id===$('#quickShiftEmployee').value),message=$('#quickShiftAvailability');if(!shift||!employee){message.classList.add('hidden');return}const unavailable=unavailableReason(employee.id,shift);message.textContent=unavailable?`${employee.full_name} er ikke tilgjengelig: ${unavailable}.`:`${employee.full_name} er tilgjengelig for denne vakten.`;message.className=`dashboard-note ${unavailable?'warning':''}`}

$('#shiftList').onclick=event=>{const button=event.target.closest('[data-shift-id]');if(button)openQuickShift(button.dataset.shiftId)};
$('#quickShiftEmployee').onchange=updateAvailability;
$('#cancelQuickShift').onclick=()=>$('#quickShiftDialog').close();
$('#quickShiftForm').onsubmit=async event=>{event.preventDefault();const shift=(rosterData.shifts||[]).find(item=>item.id===$('#quickShiftId').value),button=event.submitter,publishMode=button?.dataset.publish;if(!shift||!publishMode)return;const employeeId=$('#quickShiftEmployee').value,reason=$('#quickShiftReason').value;if(!employeeId||!reason)return show('Velg ansatt og årsak til endringen.');const original=button.textContent;button.disabled=true;button.textContent='Lagrer …';try{const week=monday(shift.work_date);await authenticated(`/functions/v1/roster?week=${week}`,{method:'POST',body:{action:'save_shift',id:shift.id,employee_id:employeeId,work_date:shift.work_date,shift_type:shift.shift_type,start_time:String(shift.start_time).slice(0,5),end_time:String(shift.end_time).slice(0,5),reason}});if(publishMode==='silent'){const result=await authenticated('/functions/v1/roster-publish-silent',{method:'POST',body:{week}});show(`Endringen er publisert uten e-post · ${result.published} vakter.`)}else{const result=await authenticated(`/functions/v1/roster?week=${week}`,{method:'PATCH',body:{action:'publish'}});show(`Endringen er publisert · e-post sendt til ${result.email_sent} av ${result.recipients}.`)}$('#quickShiftDialog').close();await loadDay()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent=original}};

function moveDay(days){selectedDate=addDays(selectedDate,days);loadDay().catch(error=>show(error.message))}
$('#previousDay').onclick=()=>moveDay(-1);$('#nextDay').onclick=()=>moveDay(1);$('#today').onclick=()=>{selectedDate=localDate();loadDay().catch(error=>show(error.message))};

$('#emailForm').onsubmit=async event=>{event.preventDefault();loginEmail=$('#email').value.trim().toLowerCase();const button=event.submitter,original=button.textContent;button.disabled=true;button.textContent='Sender kode …';try{await request('/auth/v1/otp',{method:'POST',body:{email:loginEmail,create_user:false}});$('#emailForm').classList.add('hidden');$('#codeForm').classList.remove('hidden');$('#sentTo').textContent=`Koden er sendt til ${loginEmail}.`;$('#code').focus()}catch(error){show(error.message)}finally{button.disabled=false;button.textContent=original}};
$('#back').onclick=()=>{$('#codeForm').classList.add('hidden');$('#emailForm').classList.remove('hidden')};
$('#code').oninput=event=>{event.target.value=event.target.value.replace(/\D/g,'').slice(0,8)};
$('#codeForm').onsubmit=async event=>{event.preventDefault();const token=$('#code').value.replace(/\D/g,'');if(!/^(?:\d{6}|\d{8})$/.test(token))return show('Skriv inn hele koden på seks eller åtte sifre.');const button=event.submitter,original=button.textContent;button.disabled=true;button.textContent='Kontrollerer …';try{const data=await request('/auth/v1/verify',{method:'POST',body:{email:loginEmail,token,type:'email'}});saveSession(data);await openApp()}catch{show('Koden er ugyldig eller utløpt. Be om en ny kode og prøv igjen.')}finally{button.disabled=false;button.textContent=original}};
$('#logout').onclick=async()=>{try{await authenticated('/auth/v1/logout',{method:'POST'})}catch{}saveSession(null);location.reload()};

const isStandalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const isIos=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
const installDismissedRecently=()=>Date.now()-Number(localStorage.getItem(INSTALL_DISMISSED)||0)<12096e5;
function setNetworkStatus(){$('#networkStatus').classList.toggle('hidden',navigator.onLine)}
function showInstallOffer(){if(!isStandalone()&&!installDismissedRecently())$('#pwaInstallBar').classList.remove('hidden')}
function showUpdateOffer(registration){pwaRegistration=registration;$('#pwaInstallBar').classList.add('hidden');$('#pwaUpdateBar').classList.remove('hidden')}
window.addEventListener('online',setNetworkStatus);window.addEventListener('offline',setNetworkStatus);setNetworkStatus();
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;showInstallOffer()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;$('#pwaInstallBar').classList.add('hidden');localStorage.removeItem(INSTALL_DISMISSED)});
$('#installPwa').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#pwaInstallBar').classList.add('hidden')}else if(isIos()){$('#pwaInstallBar').classList.add('hidden');$('#installHelpDialog').showModal()}};
$('#dismissPwaInstall').onclick=()=>{localStorage.setItem(INSTALL_DISMISSED,String(Date.now()));$('#pwaInstallBar').classList.add('hidden')};
$('#closeInstallHelp').onclick=()=>$('#installHelpDialog').close();$('#dismissPwaUpdate').onclick=()=>$('#pwaUpdateBar').classList.add('hidden');
$('#updatePwa').onclick=()=>{const worker=pwaRegistration?.waiting;if(worker){pwaRefreshing=true;worker.postMessage({type:'SKIP_WAITING'})}else location.reload()};
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/'});pwaRegistration=registration;if(registration.waiting)showUpdateOffer(registration);registration.addEventListener('updatefound',()=>{const worker=registration.installing;if(worker)worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdateOffer(registration)})});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(pwaRefreshing)location.reload()});registration.update().catch(()=>{})}catch(error){console.warn('ADMIN-appen kunne ikke registreres.',error)}});
if(isIos()&&!isStandalone())setTimeout(showInstallOffer,1200);

try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{session=null}
if(session?.access_token)openApp();
