/* Weekly review is ADMIN-only; all approvals, calculations and locks are verified on the server. */
let weeklyData=null,weeklyEmployeeId='',weeklyBusy=false,weeklyReport=null,weeklyEdit=null,weeklyReasonAction=null,weeklyRequest=0;
const weeklyDate=value=>new Date(`${value}T12:00:00Z`).toLocaleDateString('nb-NO',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Europe/Oslo'});
const weeklyMoney=value=>Number(value||0).toLocaleString('nb-NO',{style:'currency',currency:'NOK',maximumFractionDigits:2});
const weeklyKind=kind=>({work:'Arbeid',sick_pay:'Sykepenger',overtime_40:'Overtidstillegg 40 %',overtime_100:'Overtidstillegg 100 %',evening:'Kveldstillegg',night:'Nattillegg',weekend:'Helgetillegg'})[kind]||kind;
function weeklyMonday(value){const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-(d.getUTCDay()||7)+1);return d.toISOString().slice(0,10)}
function weeklyTitle(week){const d=new Date(`${week}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+3);const year=d.getUTCFullYear(),first=weeklyMonday(`${year}-01-04`),number=1+Math.round((new Date(`${week}T12:00:00Z`)-new Date(`${first}T12:00:00Z`))/604800000);return `Uke ${number} · ${weeklyDate(week)}–${weeklyDate(dashboardAddDays(week,6))}`}
async function loadWeeklyReview(){
 const requestId=++weeklyRequest,week=weeklyMonday($('#weeklyDate').value||dashboardAddDays(localDate(),-7));$('#weeklyDate').value=week;
 $('#weeklyMessage').textContent='Henter uken …';
 try{const data=await authenticated('/functions/v1/weekly-review',{method:'POST',body:{action:'load',week_start:week}});if(requestId!==weeklyRequest)return;weeklyData=data;weeklyReport=null;$('#weeklyReport').classList.add('hidden');renderWeeklyReview()}
 catch(error){if(requestId!==weeklyRequest)return;weeklyData=null;$('#weeklyPeople').innerHTML='';$('#weeklyEmployee').classList.add('hidden');$('#weeklyMessage').textContent=error.message;$('#weeklyLockAll').disabled=true}
}
async function weeklyAction(action,extra={}){
 if(weeklyBusy||!weeklyData)return false;weeklyBusy=true;renderWeeklyReview();
 try{weeklyData=await authenticated('/functions/v1/weekly-review',{method:'POST',body:{action,week_start:weeklyData.week_start,expected:weeklyData.fingerprint,employee_id:weeklyEmployeeId||null,...extra}});weeklyReport=null;$('#weeklyReport').classList.add('hidden');renderWeeklyReview();return true}
 catch(error){show(error.message);await loadWeeklyReview();return false}
 finally{weeklyBusy=false;renderWeeklyReview()}
}
function weeklySummaryHtml(person){const s=person.summary;return `<div class="weekly-summary"><div><span>Arbeid</span><strong>${hours(s.work_hours)}</strong></div><div><span>Sykepenger</span><strong>${hours(s.sick_hours)}</strong></div><div><span>Grunnlønn</span><strong>${weeklyMoney(s.base_cost)}</strong></div><div><span>Tillegg</span><strong>${weeklyMoney(s.premium_cost)}</strong></div><div><span>${s.cost_incomplete?'Kjent del av kostnad':'Kostnad uten sosiale kostnader'}</span><strong>${weeklyMoney(s.total_cost)}</strong></div></div>${s.cost_incomplete?'<p class="weekly-warning">Kostnaden er ufullstendig. Timesats eller en tilleggssats mangler. Fast månedslønn omregnes ikke automatisk.</p>':''}<p class="hint">Kveld: ${hours(s.evening_hours)} · Natt: ${hours(s.night_hours)} · Helg: ${hours(s.weekend_hours)} · Overtid 40 %: ${hours(s.overtime_40_hours)} · Overtid 100 %: ${hours(s.overtime_100_hours)}</p>`}
function renderWeeklyReview(){
 if(!weeklyData)return;
 const data=weeklyData,rows=data.employees||[],done=rows.filter(p=>p.locked),pending=rows.filter(p=>!p.locked),filter=$('#weeklyFilter').value;
 $('#weeklyTitle').textContent=weeklyTitle(data.week_start);
 $('#weeklyMessage').textContent=data.locked?`Hele uken er låst · rapportversjon ${data.revision}.`:`${done.length} av ${rows.length} ansatte er ferdig kontrollert. ${data.can_lock?'Uken kan sluttføres når alle er ferdige.':`Låsing åpner ${new Date(data.closes_after).toLocaleString('nb-NO',{timeZone:'Europe/Oslo'})}.`}`;
 $('#weeklyProgress').max=Math.max(1,rows.length);$('#weeklyProgress').value=done.length;
 $('#weeklyLockAll').classList.toggle('hidden',data.locked);$('#weeklyLockAll').disabled=weeklyBusy||!rows.length;
 $('#weeklyReopenAll').classList.toggle('hidden',!data.locked);$('#weeklyReopenAll').disabled=weeklyBusy;
 $('#weeklyGetReport').classList.toggle('hidden',!data.locked);$('#weeklyGetReport').disabled=weeklyBusy;
 const visible=filter==='done'?done:filter==='all'?rows:pending;
 $('#weeklyPeople').innerHTML=visible.length?visible.map(p=>`<button type="button" class="weekly-person ${weeklyEmployeeId===p.employee.id?'selected':''}" data-weekly-person="${p.employee.id}" ${weeklyBusy?'disabled':''}><strong>${escapeHtml(p.employee.full_name)}</strong><small>${p.locked?'Låst':`${p.unapproved} ubehandlet${p.open_entries?` · ${p.open_entries} åpne`:''}${p.missing_shifts?` · ${p.missing_shifts} mangler stempling`:''}`}</small></button>`).join(''):`<p class="empty">${filter==='pending'&&rows.length?'Alle ansatte er ferdig kontrollert.':'Ingen ansatte i denne listen.'}</p>`;
 const p=rows.find(x=>x.employee.id===weeklyEmployeeId);$('#weeklyEmployee').classList.toggle('hidden',!p);
 if(p){
 $('#weeklyEmployeeName').textContent=p.employee.full_name;$('#weeklyEmployeeState').textContent=p.locked?'Låst og ferdig kontrollert':`${p.unapproved} registreringer gjenstår`;
 $('#weeklyEmployeeSummary').innerHTML=weeklySummaryHtml(p);
 $('#weeklyLockEmployee').classList.toggle('hidden',p.locked);$('#weeklyLockEmployee').disabled=weeklyBusy;
 $('#weeklyReopenEmployee').classList.toggle('hidden',!p.locked);$('#weeklyReopenEmployee').disabled=weeklyBusy;
 const allItems=[...p.entries.map(e=>({...e,item_type:'entry'})),...p.adjustments.map(a=>({...a,item_type:'adjustment'}))];
 $('#weeklyDays').innerHTML=Array.from({length:7},(_,i)=>{const date=dashboardAddDays(data.week_start,i),items=allItems.filter(e=>e.work_date===date),shifts=p.shifts.filter(s=>s.work_date===date),dayName=new Date(`${date}T12:00:00Z`).toLocaleDateString('nb-NO',{weekday:'long',timeZone:'Europe/Oslo'}),unapproved=items.filter(e=>!e.approved),open=items.some(e=>e.item_type==='entry'&&!e.ended_at);
 return `<section class="weekly-day"><div class="weekly-day-head"><h4>${escapeHtml(dayName)} <small>${weeklyDate(date)}</small></h4>${!p.locked&&items.length?`<button type="button" class="small secondary" data-weekly-day="${date}" ${weeklyBusy||!unapproved.length||open?'disabled':''}>${!unapproved.length?'Dagen er godkjent':'Godkjenn dagen'}</button>`:''}</div>${shifts.length?`<div class="weekly-planned">${shifts.map(s=>`<div><span>Planlagt: ${escapeHtml(String(s.start_time).slice(0,5))}–${escapeHtml(String(s.end_time).slice(0,5))}${s.end_time<=s.start_time?' neste dag':''}</span>${!s.matched?`<span class="${s.resolved?'muted':'weekly-warning'}">${s.resolved?`Avklart: ${escapeHtml(s.reason)}`:'Mangler stempling'}</span>${!s.resolved&&!p.locked?`<button type="button" class="small" data-weekly-resolve="${escapeHtml(s.shift_key)}" ${weeklyBusy?'disabled':''}>Avklar</button>`:''}`:''}</div>`).join('')}</div>`:''}${items.length?items.map(e=>{const entry=e.item_type==='entry';return `<div class="weekly-entry ${e.approved?'approved':''}"><div><strong>${entry?`${formatTime(e.started_at)} – ${e.ended_at?formatTime(e.ended_at):'Pågår'}`:weeklyKind(e.category)}</strong>${entry&&e.ended_at&&dateTimeLocal(e.ended_at).slice(0,10)!==date?'<small>Avsluttes neste dag</small>':''}<small>${entry?`${stampReference(e)} · ${weeklyKind(e.kind)} · ${approvalSource(e.source)}${e.auto_clocked_out?' · automatisk ut':''}`:escapeHtml(e.note||'Manuelt tillegg')}</small></div><strong>${entry&&!e.ended_at?'–':hours(e.hours)}</strong><div class="weekly-entry-actions">${!p.locked&&entry?`<button type="button" class="small secondary" data-weekly-edit="${e.id}" ${weeklyBusy?'disabled':''}>${e.ended_at?'Rediger':'Avslutt'}</button><button type="button" class="small danger" data-weekly-delete="${e.id}" ${weeklyBusy||!e.ended_at?'disabled':''}>Slett</button>`:''}<label class="weekly-check"><input type="checkbox" data-weekly-approve="${e.id}" data-item-type="${e.item_type}" ${e.approved?'checked':''} ${p.locked||weeklyBusy||(entry&&!e.ended_at)?'disabled':''}> Godkjent</label></div></div>`}).join(''):'<p class="muted">Ingen registreringer.</p>'}</section>`}).join('');
 }
 $('#weeklyCompleted').innerHTML=done.length?`<h3>Ferdig kontrollert</h3>${done.map(p=>`<details class="weekly-completed"><summary>${escapeHtml(p.employee.full_name)} · ${hours(p.summary.work_hours)} arbeid · ${p.summary.cost_incomplete?'Kjent kostnad: ':''}${weeklyMoney(p.summary.total_cost)}</summary>${weeklySummaryHtml(p)}<button type="button" class="small secondary" data-weekly-person="${p.employee.id}">Vis registreringer</button></details>`).join('')}`:'';
 $('#weeklyRevisions').innerHTML=data.revisions.length?`<label>Rapportarkiv<select id="weeklyRevisionChoice">${data.revisions.map(r=>`<option value="${r.id}">Versjon ${r.revision}${r.superseded_at?' · tidligere versjon':' · gjeldende'}</option>`).join('')}</select></label><button type="button" class="secondary" id="weeklyOpenRevision">Vis rapportversjon</button>`:'';
 for(const control of document.querySelectorAll('#weeklyControls input,#weeklyControls select,#weeklyControls button'))control.disabled=weeklyBusy;
}
function weeklyReason(action,title,text,extra={}){weeklyReasonAction={action,extra};$('#weeklyReasonTitle').textContent=title;$('#weeklyReasonText').textContent=text;$('#weeklyReason').value='';$('#weeklyReasonError').textContent='';$('#weeklyReasonDialog').showModal()}
$('#weeklyDate').value=weeklyMonday(dashboardAddDays(localDate(),-7));
$('#weeklyDate').onchange=()=>{weeklyEmployeeId='';loadWeeklyReview()};
$('#weeklyRefresh').onclick=()=>loadWeeklyReview();
$('#weeklyPrevious').onclick=()=>{$('#weeklyDate').value=dashboardAddDays($('#weeklyDate').value,-7);weeklyEmployeeId='';loadWeeklyReview()};
$('#weeklyNext').onclick=()=>{$('#weeklyDate').value=dashboardAddDays($('#weeklyDate').value,7);weeklyEmployeeId='';loadWeeklyReview()};
$('#weeklyFilter').onchange=()=>renderWeeklyReview();
$('#weeklyReviewContent').onclick=async event=>{
 const person=event.target.closest('[data-weekly-person]');if(person){weeklyEmployeeId=person.dataset.weeklyPerson;renderWeeklyReview();return}
 const p=weeklyData?.employees.find(x=>x.employee.id===weeklyEmployeeId);if(!p||weeklyBusy)return;
 const day=event.target.closest('[data-weekly-day]');if(day){const date=day.dataset.weeklyDay,items=[...p.entries.filter(e=>e.work_date===date&&!e.approved).map(e=>({id:e.id,type:'entry'})),...p.adjustments.filter(e=>e.work_date===date&&!e.approved).map(e=>({id:e.id,type:'adjustment'}))];await weeklyAction('approve',{items,approved:true});return}
 const resolve=event.target.closest('[data-weekly-resolve]');if(resolve){weeklyReason('resolve_shift','Avklar manglende stempling','Hvis vakten ble arbeidet, etterregistrer den fra Vaktliste. Hvis vakten ikke ble arbeidet, skriv årsaken her. Avklaringen oppretter ingen timer eller sykepenger.',{shift_key:resolve.dataset.weeklyResolve});return}
 const remove=event.target.closest('[data-weekly-delete]');if(remove){openDeleteStamp(p.entries.find(e=>e.id===remove.dataset.weeklyDelete),p.employee.full_name);return}
 const edit=event.target.closest('[data-weekly-edit]');if(edit){weeklyEdit=p.entries.find(e=>e.id===edit.dataset.weeklyEdit);$('#weeklyEditStart').value=dateTimeLocal(weeklyEdit.started_at);$('#weeklyEditEnd').value=weeklyEdit.ended_at?dateTimeLocal(weeklyEdit.ended_at):'';$('#weeklyEditReason').value='';$('#weeklyEditError').textContent='';$('#weeklyEditDialog').showModal()}
};
$('#weeklyDays').onchange=async event=>{const input=event.target.closest('[data-weekly-approve]');if(input)await weeklyAction('approve',{items:[{id:input.dataset.weeklyApprove,type:input.dataset.itemType}],approved:input.checked})};
$('#weeklyLockEmployee').onclick=async()=>{const p=weeklyData?.employees.find(x=>x.employee.id===weeklyEmployeeId);if(!p)return;if(!weeklyData.can_lock){show('Uken kan først låses mandag kl. 08.00 norsk tid.');return}if(p.unapproved||p.open_entries||p.missing_shifts){show('Kontroller alle registreringer og avklar manglende stemplinger før du låser.');return}if(!confirm(`Låse uken for ${p.employee.full_name}?${p.summary.cost_incomplete?' Kostnadsoversikten er ufullstendig fordi satser mangler.':''}`))return;if(await weeklyAction('lock_employee'))show('Uken er låst for den ansatte. Velg neste ansatt fra listen.')};
$('#weeklyLockAll').onclick=async()=>{if(!weeklyData)return;if(!weeklyData.can_lock){show('Uken kan først låses mandag kl. 08.00 norsk tid.');return}const remaining=weeklyData.employees.filter(p=>!p.locked);if(remaining.length){show(`Uken kan ikke avsluttes. ${remaining.length} ansatte er ikke ferdig behandlet og låst.`);return}if(!confirm('Låse hele uken og opprette ukerapporten?'))return;if(await weeklyAction('lock_week')){show('Hele uken er låst. Ukerapporten er klar.');await loadWeeklyReport()}};
$('#weeklyReopenEmployee').onclick=()=>weeklyReason('reopen_employee','Gjenåpne ansattens uke','Dette åpner også den samlede uken hvis den er låst. Godkjenningene for denne ansatte nullstilles. Tidligere rapport beholdes.');
$('#weeklyReopenAll').onclick=()=>weeklyReason('reopen_week','Gjenåpne hele uken','Alle ansattes godkjenninger nullstilles. Tidligere rapport beholdes. Skriv hvorfor uken skal behandles på nytt.');
$('#weeklyReasonCancel').onclick=()=>$('#weeklyReasonDialog').close();
$('#weeklyReasonForm').onsubmit=async event=>{event.preventDefault();const reason=$('#weeklyReason').value.trim();if(reason.length<3){$('#weeklyReasonError').textContent='Skriv minst tre tegn.';return}event.submitter.disabled=true;try{if(await weeklyAction(weeklyReasonAction.action,{...weeklyReasonAction.extra,reason}))$('#weeklyReasonDialog').close()}finally{event.submitter.disabled=false}};
$('#weeklyEditCancel').onclick=()=>$('#weeklyEditDialog').close();
$('#weeklyEditForm').onsubmit=async event=>{event.preventDefault();const reason=$('#weeklyEditReason').value.trim();if(reason.length<3)return;event.submitter.disabled=true;try{const success=await weeklyAction('correct',{entry_id:weeklyEdit.id,started_at:osloWallToIso($('#weeklyEditStart').value),ended_at:osloWallToIso($('#weeklyEditEnd').value),reason});if(success){$('#weeklyEditDialog').close();show('Tidene er endret. Registreringen må godkjennes på nytt.')}}catch(error){$('#weeklyEditError').textContent=error.message}finally{event.submitter.disabled=false}};
async function loadWeeklyReport(reportId=null){if(!weeklyData)return;try{weeklyReport=await authenticated('/functions/v1/weekly-review',{method:'POST',body:{action:'report',week_start:weeklyData.week_start,...(reportId?{report_id:reportId}:{})}});renderWeeklyReport()}catch(error){show(error.message)}}
$('#weeklyGetReport').onclick=()=>loadWeeklyReport();
$('#weeklyRevisions').onclick=event=>{if(event.target.closest('#weeklyOpenRevision'))loadWeeklyReport($('#weeklyRevisionChoice').value)};
function weeklyReportLines(report){return report.employees.flatMap(p=>{const s=p.summary,rates=s.payroll_codes;return [['ordinary','Arbeid',s.work_hours,s.hourly_rate],['sick_pay','Sykepenger',s.sick_hours,s.hourly_rate],['evening','Kveldstillegg',s.evening_hours,rates.evening?.hourly_rate],['night','Nattillegg',s.night_hours,rates.night?.hourly_rate],['weekend','Helgetillegg',s.weekend_hours,rates.weekend?.hourly_rate],['overtime_40','Overtidstillegg 40 %',s.overtime_40_hours,s.hourly_rate==null?null:s.hourly_rate*.4],['overtime_100','Overtidstillegg 100 %',s.overtime_100_hours,s.hourly_rate]].filter(x=>Number(x[2])!==0).map(([key,label,amount,rate])=>({employee:p.employee.full_name,number:p.employee.employee_number,code:rates[key]?.code||'',label,hours:Number(amount),rate:rate==null?null:Number(rate),cost:rate==null?null:Number(amount)*Number(rate)}))})}
function renderWeeklyReport(){const report=weeklyReport.report,rows=report.employees,total=rows.reduce((a,p)=>({hours:a.hours+Number(p.summary.work_hours),sick:a.sick+Number(p.summary.sick_hours),cost:a.cost+Number(p.summary.total_cost),incomplete:a.incomplete||p.summary.cost_incomplete}),{hours:0,sick:0,cost:0,incomplete:false});$('#weeklyReportTitle').textContent=`Ukerapport · ${weeklyTitle(report.week_start)} · versjon ${weeklyReport.revision}`;$('#weeklyReportMeta').textContent=`Apart Stavanger AS · Låst ${new Date(weeklyReport.locked_at).toLocaleString('nb-NO',{timeZone:'Europe/Oslo'})}${weeklyReport.superseded_at?' · TIDLIGERE RAPPORTVERSJON':''}`;$('#weeklyReportTotals').innerHTML=`<div><span>Arbeidstimer</span><strong>${hours(total.hours)}</strong></div><div><span>Sykepengetimer</span><strong>${hours(total.sick)}</strong></div><div><span>${total.incomplete?'Kjent kostnad (ufullstendig)':'Samlet kostnad uten sosiale kostnader'}</span><strong>${weeklyMoney(total.cost)}</strong></div>`;$('#weeklyReportRows').innerHTML=rows.map(p=>`<tr><td>${escapeHtml(p.employee.full_name)}</td><td>${hours(p.summary.work_hours)}</td><td>${hours(p.summary.sick_hours)}</td><td>${weeklyMoney(p.summary.base_cost)}</td><td>${weeklyMoney(p.summary.premium_cost)}</td><td>${weeklyMoney(p.summary.total_cost)}${p.summary.cost_incomplete?' *':''}</td></tr>`).join('');$('#weeklyReportDetails').innerHTML=weeklyReportLines(report).map(x=>`<tr><td>${escapeHtml(x.employee)}</td><td>${escapeHtml(x.code||'Ikke satt')} · ${escapeHtml(x.label)}</td><td>${hours(x.hours)}</td><td>${x.rate==null?'Mangler':weeklyMoney(x.rate)}</td><td>${x.cost==null?'Mangler':weeklyMoney(x.cost)}</td></tr>`).join('');$('#weeklyReportWarning').textContent=total.incomplete?'* Kostnaden er ufullstendig fordi enkelte satser manglet ved låsing. Rapporten viser bare kjent kostnad.':'';$('#weeklyReport').classList.remove('hidden')}
function weeklyCsvCell(value){let s=String(value??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
$('#weeklyExportCsv').onclick=()=>{if(!weeklyReport)return;const r=weeklyReport,lines=[['Apart Stavanger AS','Ukerapport',r.report.week_start,`Versjon ${r.revision}`,r.superseded_at?'Tidligere versjon':'Gjeldende rapport'],['Ansattnummer','Navn','Lønnsart','Beskrivelse','Timer','Sats (NOK)','Beløp (NOK)'],...weeklyReportLines(r.report).map(x=>[x.number,x.employee,x.code,x.label,String(x.hours).replace('.',','),x.rate==null?'Mangler':String(x.rate).replace('.',','),x.cost==null?'Mangler':x.cost.toFixed(2).replace('.',',')])];const blob=new Blob(['\ufeff'+lines.map(row=>row.map(weeklyCsvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});weeklyDownloadBlob(blob,`apart-ukerapport-${r.report.week_start}-v${r.revision}.csv`)};
function weeklyDownloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#weeklyExportPdf').onclick=async()=>{if(!weeklyReport)return;const b=$('#weeklyExportPdf');b.disabled=true;try{const data=await authenticated('/functions/v1/weekly-review',{method:'POST',body:{action:'export_pdf',week_start:weeklyReport.report.week_start,report_id:weeklyReport.id,revision:weeklyReport.revision}});weeklyDownloadBlob(new Blob([Uint8Array.from(atob(data.content_base64),c=>c.charCodeAt(0))],{type:'application/pdf'}),data.file_name)}catch(error){show(error.message)}finally{b.disabled=false}};
