const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://apart.test',runScripts:'outside-only'}),w=dom.window;try{
 w.matchMedia=()=>({matches:false});w.confirm=()=>true;const calls=[];
 const data={month:'2026-10-01',updated_at:'2026-10-08T10:00:00Z',totals:{actual:1200,provisional:100,remaining:5000,unrecorded:1600,estimate:2000,planned:8000,forecast:9900,variance:200,compared_shifts:1},warnings:['Test <script> bad'],days:[{date:'2026-10-08',actual:1200,provisional:100,remaining:0,unrecorded:1600,estimate:0,complete:false,status:'published'}],estimated_days:2,baseline_week:'2026-09-28',baseline_confirmed:false,unapproved_count:1,open_count:1};
 const plan={date:'2026-10-08',fingerprint:'version1',complete:false,shifts:[]};
 w.fetch=async(url,options={})=>{const body=JSON.parse(options.body||'{}');calls.push(body);if(body.action==='complete_day'){assert.equal(body.expected,'version1');assert.equal(body.complete,true);plan.complete=true}return new Response(JSON.stringify(body.action==='load'?data:{days:[plan]}))};
 w.eval(fs.readFileSync('app.js','utf8')+'\n'+fs.readFileSync('weekly-review.js','utf8')+'\n'+fs.readFileSync('payroll-dashboard.js','utf8')+`;window.costTest={init:()=>{saveSession({access_token:'synthetic',expires_at:Date.now()/1000+3600});currentEmployee={role:'admin'};rosterWeekStart='2026-10-05'},load:loadPayrollDashboard,planning:loadRosterPlanning};`);
 await new Promise(r=>setTimeout(r,0));w.costTest.init();await w.costTest.load();assert.equal(w.document.querySelectorAll('.payroll-cost-stat').length,4);assert.match(w.document.querySelector('#payrollCostContent').textContent,/9\s?900/);assert.equal(w.document.querySelector('#payrollCostWarnings script'),null);assert.equal(w.document.querySelector('#payrollCostContent').classList.contains('hidden'),false);
 await w.costTest.planning();const checkbox=w.document.querySelector('[data-plan-date]');checkbox.checked=true;checkbox.dispatchEvent(new w.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,20));assert.equal(w.document.querySelector('[data-plan-date]').checked,true);assert.match(w.document.querySelector('#rosterPlanningDays').textContent,/Ferdig/);
 w.document.querySelector('#payrollCostMonth').value='2026-11';w.document.querySelector('#payrollCostMonth').dispatchEvent(new w.Event('change'));await new Promise(r=>setTimeout(r,20));assert.equal(calls.at(-1).month,'2026-11-01');console.log('PASS: cards, escaped warnings, monthly selection, completion checkbox and fingerprint');
 }finally{w.close()}})().catch(e=>{console.error(e);process.exitCode=1});
