const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');
const compile=p=>stripTypeScriptTypes(fs.readFileSync(p,'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,''));
const premium=new Function(compile('supabase/functions/_shared/payroll-premiums.ts')+';return premiumHoursBetween')();
const {payrollForecast,shiftBounds}=new Function('premiumHoursBetween',compile('supabase/functions/_shared/payroll-forecast.ts')+';return {payrollForecast,shiftBounds}')(premium);
const rates={evening:{hourly_rate:10},night:{hourly_rate:20},weekend:{hourly_rate:30}};
const shift=(date='2026-10-08',patch={})=>({id:'s',employee_id:'e',work_date:date,start_time:'08:00',end_time:'16:00',shift_type:'day',...patch});
const entry=(patch={})=>({id:'t',employee_id:'e',work_date:'2026-10-08',started_at:'2026-10-08T06:00:00Z',ended_at:'2026-10-08T14:00:00Z',kind:'work',scheduled_shift_id:'s',approved:true,...patch});
const fixture=(patch={})=>({month:'2026-10-01',now:'2026-10-08T18:00:00Z',days:[{date:'2026-10-08',shifts:[shift()],complete:true,status:'published'}],employees:[{id:'e',hourly_rate:200,active:true}],rates,baseline:[],weeks:[{week_start:'2026-10-05',employees:[{employee:{id:'e'},summary:{hourly_rate:200,payroll_codes:rates},entries:[entry()],adjustments:[],shifts:[],locked:false}]}],...patch});
test('completed shifts replace plans; actual overtime hours create deviation without duplicate planned cost',()=>{const d=fixture();d.weeks[0].employees[0].entries[0].ended_at='2026-10-08T15:00:00Z';const r=payrollForecast(d);assert.equal(r.totals.actual,1800);assert.equal(r.totals.planned,1600);assert.equal(r.totals.forecast,1800);assert.equal(r.totals.variance,200)});
test('missing punches retain planned cost while resolutions remove them',()=>{const d=fixture();d.weeks[0].employees[0].entries=[];let r=payrollForecast(d);assert.equal(r.totals.actual,0);assert.equal(r.totals.unrecorded,1600);assert.equal(r.missing_shifts,1);d.weeks[0].employees[0].shifts=[{id:'s',resolved:true}];r=payrollForecast(d);assert.equal(r.totals.forecast,0)});
test('open entry contributes elapsed cost plus only remaining shift, abnormal open warns',()=>{const d=fixture({now:'2026-10-08T10:00:00Z'});d.weeks[0].employees[0].entries=[entry({ended_at:null})];let r=payrollForecast(d);assert.equal(r.totals.provisional,800);assert.equal(r.totals.remaining,800);assert.equal(r.totals.forecast,1600);d.now='2026-10-09T18:00:00Z';r=payrollForecast(d);assert.equal(r.totals.provisional,0);assert.equal(r.totals.unrecorded,1600);assert.equal(r.long_open_count,1)});
test('same weekday baseline fills only missing slots; completion suppresses inferred shifts including empty days',()=>{const d=fixture({now:'2026-10-07T18:00:00Z',weeks:[],baseline_week:'2026-09-28',baseline:[{date:'2026-10-01',shifts:[shift('2026-10-01'),shift('2026-10-01',{id:'s2'})]}]});d.days[0].complete=false;let r=payrollForecast(d);assert.equal(r.totals.remaining,1600);assert.equal(r.totals.estimate,1600);assert.equal(r.totals.forecast,3200);d.days[0].complete=true;r=payrollForecast(d);assert.equal(r.totals.estimate,0);d.days[0].shifts=[];assert.equal(payrollForecast(d).totals.forecast,0)});
test('sick entries and adjustments carry no premiums and replace missing planned hours',()=>{const d=fixture();d.days[0].shifts=[shift('2026-10-08',{start_time:'00:00',end_time:'06:00'})];d.weeks[0].employees[0].entries=[entry({kind:'sick_pay',started_at:'2026-10-07T22:00:00Z',ended_at:'2026-10-08T04:00:00Z'})];let r=payrollForecast(d);assert.equal(r.totals.actual,1200);assert.equal(r.totals.forecast,1200);d.weeks[0].employees[0].entries=[];d.weeks[0].employees[0].adjustments=[{work_date:'2026-10-08',hours:6,category:'sick_pay'}];r=payrollForecast(d);assert.equal(r.totals.forecast,1200);assert.equal(r.missing_shifts,0)});
test('locked snapshot rates survive current rate changes; missing rates make forecast incomplete',()=>{const d=fixture();d.employees[0].hourly_rate=400;d.weeks[0].employees[0].locked=true;let r=payrollForecast(d);assert.equal(r.totals.actual,1600);assert.equal(r.totals.planned,1600);d.weeks[0].employees[0].summary.hourly_rate=null;r=payrollForecast(d);assert.equal(r.incomplete,true)});
test('night shifts allocated to start month; daylight-saving nights use actual elapsed hours',()=>{const d=fixture();d.days=[{date:'2026-10-31',shifts:[shift('2026-10-31',{start_time:'23:00',end_time:'07:00'})],complete:true}];d.weeks=[];const r=payrollForecast(d);assert.equal(r.totals.remaining,1780);const a=shiftBounds(shift('2026-10-25',{start_time:'00:00',end_time:'06:00'}));assert.equal((a.b-a.a)/3600000,7);const b=shiftBounds(shift('2026-03-29',{start_time:'00:00',end_time:'06:00'}));assert.equal((b.b-b.a)/3600000,5)});
test('absent baseline produces warning rather than pretending zero is a complete estimate',()=>{const d=fixture({weeks:[]});d.days=[{date:'2026-10-09',shifts:[],complete:false}];const r=payrollForecast(d);assert.equal(r.incomplete,true);assert.equal(r.uncovered_days,1)});
const source=compile('supabase/functions/payroll-dashboard/index.ts');
function api(role='admin'){let handler;const calls=[];const db={auth:{getUser:async()=>({data:{user:{id:'actor'}}})},from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{organization_id:'org',role,active:true}})}),rpc:async(name,args)=>(calls.push(args),{data:{days:[]}})};vm.runInNewContext(source,{Deno:{env:{get:()=>''},serve:f=>handler=f},createClient:()=>db,payrollForecast:()=>({totals:{}}),Request,Response,console:{error(){}}});return {calls,call:async(body,auth=true)=>handler(new Request('https://test.invalid',{method:'POST',headers:auth?{Authorization:'Bearer synthetic'}:{},body:JSON.stringify(body)}))}}
test('endpoint enforces ADMIN, server-derived identity, valid calendar date and action',async()=>{assert.equal((await api('employee').call({month:'2026-10-01'})).status,403);assert.equal((await api().call({},false)).status,401);for(const body of [{month:'2026-02-30'},{month:'2026-10-01',action:'delete'},{month:'2026-10-01',action:'complete_day',date:'2026-10-08',complete:'true'}])assert.equal((await api().call(body)).status,400);const f=api();assert.equal((await f.call({month:'2026-10-01',organization_id:'forged',actor:'forged'})).status,200);assert.equal(f.calls[0].p_org,'org');assert.equal(f.calls[0].p_actor,'actor')});
