const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');
const premiumSource=stripTypeScriptTypes(fs.readFileSync('supabase/functions/_shared/payroll-premiums.ts','utf8')).replace(/^export /gm,'');
const premiumHoursBetween=vm.runInNewContext(premiumSource+';premiumHoursBetween');
const compiled=stripTypeScriptTypes(fs.readFileSync('supabase/functions/admin-reports/index.ts','utf8').replace(/^import .*;\n/gm,''));
test('report API awards evening/night/weekend only to work, never to sick pay or open entries',async()=>{
 const entries=[{id:'work',employee_id:'one',kind:'work',started_at:'2025-06-02T19:00:00Z',ended_at:'2025-06-03T05:00:00Z'}, {id:'sick',employee_id:'two',kind:'sick_pay',started_at:'2025-06-02T19:00:00Z',ended_at:'2025-06-03T05:00:00Z'},{id:'open',employee_id:'one',kind:'work',started_at:'2025-06-03T19:00:00Z',ended_at:null}];
 let handler;const db={auth:{getUser:async()=>({data:{user:{id:'admin'}}})},from(table){const filters=[],b={};for(const key of ['select','eq','gte','lte','order'])b[key]=(...args)=>{filters.push([key,...args]);return b};const result=()=>{if(table==='employees'&&filters.some(x=>x[1]==='auth_user_id'))return{data:{organization_id:'org',active:true,role:'admin'}};assert.ok(filters.some(x=>x[1]==='organization_id'&&x[2]==='org'));return{data:table==='employees'?[{id:'one'},{id:'two'}]:table==='time_entries'?entries:[]}};b.maybeSingle=async()=>result();b.then=(a,c)=>Promise.resolve(result()).then(a,c);return b}};
 vm.runInNewContext(compiled,{Deno:{env:{get:()=>''},serve:f=>handler=f},createClient:()=>db,premiumHoursBetween,Response,Request,console});
 const r=await handler(new Request('https://test.invalid/',{method:'POST',headers:{Authorization:'Bearer synthetic'},body:JSON.stringify({from:'2025-06-01',to:'2025-06-30'})}));assert.equal(r.status,200);const data=await r.json();assert.deepEqual(data.entries.find(x=>x.id==='work').premium_hours,{evening:3,night:6,weekend:0});for(const id of ['sick','open'])assert.deepEqual(data.entries.find(x=>x.id===id).premium_hours,{evening:0,night:0,weekend:0});
});
test('shared payroll engine handles Sunday night and daylight-saving transitions',()=>{const sunday=premiumHoursBetween('2025-06-07T21:00:00Z','2025-06-08T05:00:00Z');assert.equal(sunday.night,6);assert.equal(sunday.weekend,2);assert.equal(sunday.evening,0);const dst=premiumHoursBetween('2025-10-25T21:00:00Z','2025-10-26T06:00:00Z');assert.equal(dst.night,7);assert.equal(dst.weekend,2)});
