const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const reportSource=stripTypeScriptTypes(fs.readFileSync('supabase/functions/_shared/weekly-report.ts','utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,''));
const reportModule=new Function('PDFDocument','StandardFonts','rgb',reportSource+';return {weeklyReportPdf,weeklyPayrollLines}')(PDFDocument,StandardFonts,rgb);
const summary={work_hours:37.5,sick_hours:4,evening_hours:3,night_hours:12,weekend_hours:6,overtime_40_hours:1,overtime_100_hours:0,hourly_rate:200,base_cost:8300,premium_cost:534.02,total_cost:8834.02,cost_incomplete:false,payroll_codes:{evening:{code:'10105',hourly_rate:12.2},night:{code:'10104',hourly_rate:23.19},weekend:{code:'10106',hourly_rate:23.19}}};
const report={id:'lock',report:{week_start:'2026-09-28',week_end:'2026-10-04',employees:[{employee:{full_name:'Eksempel Ansatt',employee_number:'001'},summary}]},revision:1,locked_at:'2026-10-05T06:10:00Z'};
test('PDF includes snapshot totals and wage lines, landscape pages and repeats page headers',async()=>{
 const rows=reportModule.weeklyPayrollLines(report.report);assert.equal(rows.find(x=>x.code==='10105').hours,3);assert.equal(rows.find(x=>x.label==='Overtidstillegg 40 %').rate,80);assert.equal(rows.find(x=>x.label==='Sykepenger').cost,800);
 const bytes=await reportModule.weeklyReportPdf(report);const pdf=await PDFDocument.load(bytes);assert.equal(pdf.getPageCount(),2);assert.ok(pdf.getPage(0).getWidth()>pdf.getPage(0).getHeight());fs.mkdirSync('tmp/pdfs',{recursive:true});fs.writeFileSync('tmp/pdfs/weekly-report.pdf',bytes);
 const many={...report,superseded_at:'2026-10-06T12:00:00Z',report:{...report.report,employees:Array.from({length:25},(_,i)=>({employee:{full_name:`Anne-Marie Østergård Eksempelnavn ${i}`,employee_number:String(i)},summary:{...summary,cost_incomplete:i===0,hourly_rate:i===0?null:200}}))}};const b=await reportModule.weeklyReportPdf(many);assert.ok((await PDFDocument.load(b)).getPageCount()>3);fs.writeFileSync('tmp/pdfs/weekly-report-long.pdf',b);
});
const source=stripTypeScriptTypes(fs.readFileSync('supabase/functions/weekly-review/index.ts','utf8').replace(/^import .*;\n/gm,''));
function fixture(opt={}){let handler;const calls=[];const db={auth:{getUser:async()=>({data:{user:opt.invalid?null:{id:'actor'}}})},from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{organization_id:'org',active:!opt.inactive,role:opt.role||'admin'}})}),rpc:async(name,args)=>{calls.push({name,args});return opt.error?{error:{code:'P0001',message:'Uken er låst.'}}:{data:report}}};vm.runInNewContext(source,{Deno:{env:{get:()=>''},serve:fn=>handler=fn},createClient:()=>db,weeklyReportPdf:async()=>new Uint8Array([1,2,3]),Request,Response,btoa,console:{error(){}}});return{calls,call:async(body,auth=true)=>{const response=await handler(new Request('https://test.invalid',{method:'POST',headers:auth?{Authorization:'Bearer synthetic'}:{},body:JSON.stringify(body)}));return{status:response.status,data:await response.json()}}}}
test('weekly endpoints enforce active ADMIN and ignore supplied actor or organization',async()=>{const body={action:'load',week_start:'2026-09-28',p_org:'forged',p_actor:'forged'};for(const opt of [{invalid:true},{inactive:true},{role:'employee'}]){const f=fixture(opt);assert.ok([401,403].includes((await f.call(body)).status));assert.equal(f.calls.length,0)}assert.equal((await fixture().call(body,false)).status,401);const f=fixture();assert.equal((await f.call(body)).status,200);assert.equal(f.calls[0].args.p_org,'org');assert.equal(f.calls[0].args.p_actor,'actor')});
test('invalid week/actions rejected; lock failures propagate; exports use frozen report RPC',async()=>{for(const patch of [{week_start:'2026-09-29'},{week_start:'wrong'},{action:'unknown'},{employee_id:'wrong'}])assert.equal((await fixture().call({action:'load',week_start:'2026-09-28',...patch})).status,400);assert.equal((await fixture({error:true}).call({action:'lock_week',week_start:'2026-09-28'})).data.error,'Uken er låst.');const f=fixture(),r=await f.call({action:'export_pdf',week_start:'2026-09-28'});assert.equal(f.calls[0].args.p_action,'report');assert.equal(r.data.file_name,'apart-ukerapport-2026-09-28-v1.pdf')});
