import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.116.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const monthPattern=/^\d{4}-(0[1-9]|1[0-2])$/;
const osloDate=(value:string)=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Oslo"}).format(new Date(value));
const osloMonth=(value:string)=>osloDate(value).slice(0,7);
const range=(monthStart:string)=>{const from=new Date(`${monthStart}T00:00:00Z`);from.setUTCDate(from.getUTCDate()-1);const to=new Date(`${monthStart}T00:00:00Z`);to.setUTCMonth(to.getUTCMonth()+1);to.setUTCDate(to.getUTCDate()+1);return{from:from.toISOString(),to:to.toISOString()}};
const entryHours=(entry:{started_at:string;ended_at:string|null})=>entry.ended_at?Math.max(0,(new Date(entry.ended_at).getTime()-new Date(entry.started_at).getTime())/3600000):0;

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  if(req.method!=="POST")return json({error:"Handling støttes ikke."},405);
  const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return json({error:"Mangler innlogging."},401);
  const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
  const {data:authData,error:authError}=await admin.auth.getUser(auth.slice(7));if(authError||!authData.user)return json({error:"Ugyldig innlogging."},401);
  const {data:me}=await admin.from("employees").select("id,organization_id,role,active").eq("auth_user_id",authData.user.id).maybeSingle();if(!me?.active||me.role!=="admin")return json({error:"Kun administrator har tilgang."},403);
  let body:Record<string,unknown>;try{body=await req.json()}catch{return json({error:"Ugyldig forespørsel."},400)}
  const action=String(body.action||"load"),month=String(body.month||"");if(!monthPattern.test(month))return json({error:"Velg en gyldig måned."},400);
  const monthStart=`${month}-01`,bounds=range(monthStart),nextMonthStart=new Date(`${monthStart}T00:00:00Z`);nextMonthStart.setUTCMonth(nextMonthStart.getUTCMonth()+1);const nextMonth=nextMonthStart.toISOString().slice(0,10);
  const {data:monthLock}=await admin.from("month_locks").select("id,locked_at,revision").eq("organization_id",me.organization_id).eq("month_start",monthStart).is("superseded_at",null).maybeSingle();
  const loadMonth=async()=>{const [{data:employees,error:employeesError},{data:rawEntries,error:entriesError},{data:adjustments,error:adjustmentsError},{data:approvals,error:approvalsError}]=await Promise.all([
    admin.from("employees").select("id,employee_number,full_name,active").eq("organization_id",me.organization_id).order("full_name"),
    admin.from("time_entries").select("id,employee_id,kind,started_at,ended_at,source,auto_clocked_out,note").eq("organization_id",me.organization_id).gte("started_at",bounds.from).lt("started_at",bounds.to).order("started_at"),
    admin.from("payroll_adjustments").select("employee_id,work_date,category,hours").eq("organization_id",me.organization_id).gte("work_date",monthStart).lt("work_date",nextMonth),
    admin.from("month_approvals").select("employee_id,status,approved_at").eq("organization_id",me.organization_id).eq("month_start",monthStart),
  ]);const error=employeesError||entriesError||adjustmentsError||approvalsError;if(error)throw new Error(error.message);return{employees:employees||[],entries:(rawEntries||[]).filter(e=>osloMonth(e.started_at)===month),adjustments:adjustments||[],approvals:approvals||[]}};
  if(action==="overview"||action==="lock_month"){
    let data;try{data=await loadMonth()}catch(error){return json({error:error instanceof Error?error.message:"Kunne ikke hente måneden."},400)}
    const relevantIds=new Set([...data.entries.map(e=>e.employee_id),...data.adjustments.map(a=>a.employee_id)]),approvalMap=new Map(data.approvals.map(a=>[a.employee_id,a]));
    const rows=data.employees.filter(e=>relevantIds.has(e.id)).map(e=>{const entries=data.entries.filter(x=>x.employee_id===e.id),approval=approvalMap.get(e.id);return{...e,status:monthLock?"locked":approval?.status||"open",approved_at:approval?.approved_at||null,entries:entries.length,hours:entries.reduce((sum,x)=>sum+entryHours(x),0),open_entries:entries.filter(x=>!x.ended_at).length}});
    if(action==="overview")return json({month,status:monthLock?"locked":"open",locked_at:monthLock?.locked_at||null,revision:monthLock?.revision||null,employees:rows});
    if(monthLock)return json({error:"Måneden er allerede låst."},409);if(!rows.length)return json({error:"Måneden har ingen registreringer."},409);if(rows.some(r=>r.open_entries>0))return json({error:"Alle åpne registreringer må stemples ut før måneden låses."},409);if(rows.some(r=>r.status!=="approved"))return json({error:"Alle ansatte med registreringer må være godkjent før måneden låses."},409);
    const {data:settings,error:settingsError}=await admin.from("payroll_settings").select("category,payroll_code,label").eq("organization_id",me.organization_id);if(settingsError)return json({error:settingsError.message},400);const payrollCodes=Object.fromEntries((settings||[]).map(s=>[s.category,{code:s.payroll_code,label:s.label}]));
    const {data:lock,error:lockError}=await admin.from("month_locks").insert({organization_id:me.organization_id,month_start:monthStart,revision:1,locked_by:authData.user.id}).select("id,locked_at,revision").single();if(lockError)return json({error:lockError.message},409);
    const snapshots=rows.map(employee=>{const entries=data.entries.filter(e=>e.employee_id===employee.id),adjustments=data.adjustments.filter(a=>a.employee_id===employee.id);return{lock_id:lock.id,employee_id:employee.id,employee_number:employee.employee_number,employee_name:employee.full_name,ordinary_hours:entries.filter(e=>e.kind==="work").reduce((s,e)=>s+entryHours(e),0),sick_pay_hours:entries.filter(e=>e.kind==="sick_pay").reduce((s,e)=>s+entryHours(e),0),overtime_40_hours:adjustments.filter(a=>a.category==="overtime_40").reduce((s,a)=>s+Number(a.hours),0),overtime_100_hours:adjustments.filter(a=>a.category==="overtime_100").reduce((s,a)=>s+Number(a.hours),0),payroll_codes:payrollCodes}});
    const inserted=await admin.from("month_snapshot_rows").insert(snapshots);if(inserted.error){await admin.from("month_locks").delete().eq("id",lock.id);return json({error:inserted.error.message},400)}
    const locked=await admin.from("month_approvals").update({status:"locked"}).eq("organization_id",me.organization_id).eq("month_start",monthStart).in("employee_id",rows.map(r=>r.id));if(locked.error){await admin.from("month_snapshot_rows").delete().eq("lock_id",lock.id);await admin.from("month_locks").delete().eq("id",lock.id);return json({error:locked.error.message},400)}
    await admin.from("audit_logs").insert({organization_id:me.organization_id,actor_id:authData.user.id,action:"lock_month",entity_type:"month_lock",entity_id:lock.id,details:{month_start:monthStart,revision:lock.revision,employees:rows.length}});return json({ok:true,lock,employees:rows.length});
  }
  const employeeId=String(body.employee_id||"");if(!employeeId)return json({error:"Velg en ansatt."},400);const {data:employee}=await admin.from("employees").select("id,employee_number,full_name").eq("id",employeeId).eq("organization_id",me.organization_id).maybeSingle();if(!employee)return json({error:"Ansatt ble ikke funnet."},404);
  if(action==="correct"){
    if(monthLock)return json({error:"Måneden er låst og kan ikke endres."},409);const entryId=String(body.entry_id||""),reason=String(body.reason||"").trim(),startedAt=String(body.started_at||""),endedAt=String(body.ended_at||"");if(reason.length<3)return json({error:"Skriv en begrunnelse på minst tre tegn."},400);
    const start=new Date(startedAt),end=new Date(endedAt);if(!entryId||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)return json({error:"Kontroller inn- og uttid."},400);if(osloMonth(startedAt)!==month||osloMonth(endedAt)!==month)return json({error:"Tidene må være innenfor valgt måned."},400);
    const {data:before}=await admin.from("time_entries").select("id,employee_id,started_at,ended_at,source,note").eq("id",entryId).eq("employee_id",employeeId).eq("organization_id",me.organization_id).maybeSingle();if(!before)return json({error:"Registreringen ble ikke funnet."},404);
    const note=[before.note,`Korrigert av admin: ${reason}`].filter(Boolean).join("\n"),{data:entry,error}=await admin.from("time_entries").update({started_at:start.toISOString(),ended_at:end.toISOString(),source:"manual",note,updated_at:new Date().toISOString()}).eq("id",entryId).select("id,started_at,ended_at,source,auto_clocked_out,note,kind").single();if(error)return json({error:error.message},400);
    await admin.from("month_approvals").update({status:"open",approved_by:null,approved_at:null}).eq("organization_id",me.organization_id).eq("employee_id",employeeId).eq("month_start",monthStart);await admin.from("audit_logs").insert({organization_id:me.organization_id,actor_id:authData.user.id,action:"correct_time_entry",entity_type:"time_entry",entity_id:entryId,details:{employee_id:employeeId,reason,before:{started_at:before.started_at,ended_at:before.ended_at,source:before.source},after:{started_at:entry.started_at,ended_at:entry.ended_at,source:entry.source}}});return json({entry});
  }
  if(action==="approve"){
    if(monthLock)return json({error:"Måneden er allerede låst."},409);const {data:entries}=await admin.from("time_entries").select("id,started_at,ended_at").eq("employee_id",employeeId).gte("started_at",bounds.from).lt("started_at",bounds.to);const relevant=(entries||[]).filter(e=>osloMonth(e.started_at)===month);if(relevant.some(e=>!e.ended_at))return json({error:"Måneden har åpne registreringer og kan ikke godkjennes."},409);
    const now=new Date().toISOString(),{data:existing}=await admin.from("month_approvals").select("employee_id,status").eq("organization_id",me.organization_id).eq("employee_id",employeeId).eq("month_start",monthStart).maybeSingle(),values={status:"approved",approved_by:authData.user.id,approved_at:now};const result=existing?await admin.from("month_approvals").update(values).eq("organization_id",me.organization_id).eq("employee_id",employeeId).eq("month_start",monthStart):await admin.from("month_approvals").insert({organization_id:me.organization_id,employee_id:employeeId,month_start:monthStart,...values});if(result.error)return json({error:result.error.message},400);
    await admin.from("audit_logs").insert({organization_id:me.organization_id,actor_id:authData.user.id,action:"approve_employee_month",entity_type:"employee",entity_id:employeeId,details:{month_start:monthStart}});return json({ok:true});
  }
  if(action!=="load")return json({error:"Ukjent handling."},400);const [{data:allEntries,error:entriesError},{data:approval,error:approvalError}]=await Promise.all([admin.from("time_entries").select("id,kind,started_at,ended_at,source,auto_clocked_out,note").eq("employee_id",employeeId).gte("started_at",bounds.from).lt("started_at",bounds.to).order("started_at"),admin.from("month_approvals").select("status,approved_at").eq("organization_id",me.organization_id).eq("employee_id",employeeId).eq("month_start",monthStart).maybeSingle()]);if(entriesError||approvalError)return json({error:entriesError?.message||approvalError?.message},400);
  return json({employee,month,entries:(allEntries||[]).filter(e=>osloMonth(e.started_at)===month),status:monthLock?"locked":approval?.status||"open",approved_at:approval?.approved_at||null,locked_at:monthLock?.locked_at||null});
});
