create policy "Organizations use protected service" on public.organizations for all to authenticated using (false) with check (false);
create policy "Worksites use protected service" on public.worksites for all to authenticated using (false) with check (false);
create policy "QR codes use protected service" on public.qr_codes for all to authenticated using (false) with check (false);
create policy "Time entries use protected service" on public.time_entries for all to authenticated using (false) with check (false);
create policy "Payroll settings use protected service" on public.payroll_settings for all to authenticated using (false) with check (false);
create policy "Payroll adjustments use protected service" on public.payroll_adjustments for all to authenticated using (false) with check (false);
create policy "Month approvals use protected service" on public.month_approvals for all to authenticated using (false) with check (false);
create policy "Month locks use protected service" on public.month_locks for all to authenticated using (false) with check (false);
create policy "Month snapshots use protected service" on public.month_snapshot_rows for all to authenticated using (false) with check (false);
create policy "Report recipients use protected service" on public.report_recipients for all to authenticated using (false) with check (false);
create policy "Audit logs use protected service" on public.audit_logs for all to authenticated using (false) with check (false);
create policy "Daily reports use protected service" on public.daily_reports for all to authenticated using (false) with check (false);
create policy "Daily report rows use protected service" on public.daily_report_rows for all to authenticated using (false) with check (false);
create policy "Transport proposals use protected service" on public.transport_transfer_proposals for all to authenticated using (false) with check (false);
create policy "HMS documents use protected service" on public.hms_documents for all to authenticated using (false) with check (false);
create policy "HMS deviations use protected service" on public.hms_deviations for all to authenticated using (false) with check (false);
create policy "Sick leave uses protected service" on public.sick_leave_requests for all to authenticated using (false) with check (false);
create policy "Vacation requests use protected service" on public.vacation_requests for all to authenticated using (false) with check (false);
create policy "Vacation carryover uses protected service" on public.vacation_carryover_requests for all to authenticated using (false) with check (false);

create index daily_report_rows_employee_idx on public.daily_report_rows(employee_id);
create index daily_reports_locked_by_idx on public.daily_reports(locked_by);
create index daily_reports_sent_by_idx on public.daily_reports(sent_by);
create index employees_deactivated_by_idx on public.employees(deactivated_by);
create index hms_deviations_handled_by_idx on public.hms_deviations(handled_by);
create index hms_documents_uploaded_by_idx on public.hms_documents(uploaded_by);
create index transport_transfer_proposals_employee_idx on public.transport_transfer_proposals(employee_id);
create index transport_transfer_proposals_report_row_idx on public.transport_transfer_proposals(report_row_id);
create index vacation_carryover_handled_by_idx on public.vacation_carryover_requests(handled_by);
create index vacation_requests_handled_by_idx on public.vacation_requests(handled_by);
